### ISSUE TITLE
Try catch 

### ISSUE THREAD

**Issue by lionelfleury** [lionelfleury/Kotlin-Scala.js#31]
- Scala.js IR only catches one parameter
- Transform the list of catches into if then else
- put per default throw for uncarched types 
- implement JS exceptions (maybe put it in another issue as it's a specific task)

**Comment by ex0ns** [comment]
It seems that Kotlin (even if there is an Array of catches in the IR...) does not support multiple catches (http://stackoverflow.com/questions/36760489/how-to-catch-many-exceptions-at-the-same-time-on-kotlin)
